name: Initial build dist

on:
  workflow_dispatch:   # запуск руками из GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
